import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="histox",
    version="0.1.0",
    cmdclass={},
    author="Lei Cao",
    author_email="caolei@hrbmu.edu.cn",
    description="Deep learning tools for digital histology",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/leicaohmu/histox",
    packages=setuptools.find_packages(),
    scripts=['scripts/histox-studio'],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    package_data={
        'histox': ['norm/norm_tile.jpg'],
    },
    python_requires='>=3.7',
    install_requires=[
        'gast>=0.3.3',
        'scipy',
        'scikit-learn',
        'matplotlib>=3.2',
        'imageio',
        'opencv-python-headless',
        'shapely',
        'umap-learn',
        'seaborn<0.14',
        'pandas',
        'pyvips',
        'fpdf2',
        'scikit-image',
        'tqdm',
        'click',
        'protobuf<3.21',
        'tensorboard',
        'crc32c',
        'numpy',
        'tabulate',
        'rasterio',
        'smac==1.4.0',
        'ConfigSpace',
        'rich',
        'pillow>=6.0.0',
        'imgui>=2.0.0',
        'pyopengl',
        'glfw',
        'saliency',
        'pyperclip',
        'requests',
        'parameterized',
        'zarr',
        'gdown',
        'triangle',
        'pyarrow',
    ],
    extras_require={
        'cucim': ['cucim'],
        'torch': [
            'torch', 'torchvision', 'pretrainedmodels',
            'cellpose<2.2', 'spacy<3.8', 'fastai',
            'pytorch-lightning', 'timm',
            'segmentation-models-pytorch',
        ],
        'tf': [
            'tensorflow>=2.7,<2.12',
            'tensorflow_probability<0.20',
            'tensorflow_datasets<4.9.0',
        ],
    },
)
